# Generated by Django 6.0.4 on 2026-04-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ambulance', 'Ambulance'), ('blood', 'Blood'), ('fire_truck', 'Fire Truck')], max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
