# Generated by Django 6.0 on 2026-04-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('volunteer', 'Volunteer'), ('authority', 'Authority')], max_length=20, null=True),
        ),
    ]
