# Generated by Django 6.0 on 2026-04-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_role_set',
            field=models.BooleanField(default=False),
        ),
    ]
